# **Notebook 2 – Data Inspection**

In [45]:
# Import Required Libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [46]:
# Dataset from kaggle
import kagglehub
path = kagglehub.dataset_download("yeanzc/telco-customer-churn-ibm-dataset")
print("Path to dataset files:", path)

Path to dataset files: C:\Users\iamna\.cache\kagglehub\datasets\yeanzc\telco-customer-churn-ibm-dataset\versions\1

In [47]:
# View files - downloaded dataset
import os
os.listdir(path)

['Telco_customer_churn.xlsx']

In [48]:
# Load dataset
df = pd.read_excel(path + "/Telco_customer_churn.xlsx")

## **1. Number of Rows**



**Understand the Concept**

The number of rows shows the total number of records in a dataset.

**Demonstrate the Concept**

In our dataset, each row represents one telecom customer.

**Real-Life Example**

If a company has 7,043 customers, the dataset contains 7,043 rows.

**AI/ML Usage**

Knowing the number of rows helps us understand the dataset size.

In [49]:
# Number of Rows - shape[0]
number_of_rows = df.shape[0]
print("Number of rows:", number_of_rows)

Number of rows: 7043

**Interpretation**

- The dataset contains 7,043 rows.
- Each row represents one customer.

## **2. Number of Columns**



**Understand the Concept**

The number of columns shows the total number of variables or features in a dataset.

**Demonstrate the Concept**

In our dataset, each column contains a different type of information about a customer.

**Real-Life Example**

A telecom company may store customer details such as Gender, Contract, Monthly Charge, and Churn Label in different columns.

**AI/ML Usage**

Knowing the number of columns helps us understand how many features are available.

In [50]:
# Number of Columns - shape[1]
number_of_columns = df.shape[1] # index 1
print("Number of columns:", number_of_columns)

Number of columns: 33

**Interpretation**

- The dataset contains 33 columns.
- Each column contains different information about customers.

## **3. Data Types**



**Understand the Concept**

Data types show the type of values stored in each column.

**Demonstrate the Concept**

Common data types include numbers, text, and dates.


**Real-Life Example**

In our dataset, Tenure Months contains numerical values, while Gender contains text values.

**AI/ML Usage**

Data types help us understand how each column should be handled before Machine Learning.

In [51]:
# data types of all columns
df.dtypes

CustomerID            object
Count                  int64
Country               object
State                 object
City                  object
Zip Code               int64
Lat Long              object
Latitude             float64
Longitude            float64
Gender                object
Senior Citizen        object
Partner               object
Dependents            object
Tenure Months          int64
Phone Service         object
Multiple Lines        object
Internet Service      object
Online Security       object
Online Backup         object
Device Protection     object
Tech Support          object
Streaming TV          object
Streaming Movies      object
Contract              object
Paperless Billing     object
Payment Method        object
Monthly Charges      float64
Total Charges         object
Churn Label           object
Churn Value            int64
Churn Score            int64
CLTV                   int64
Churn Reason          object
dtype: object

**Interpretation**

- The output shows the data type of each column.
- Numerical columns contain number-based values.
- Text columns contain categorical or string values.

## **4. Column Names**



**Understand the Concept**

Column names identify the information stored in each column.

**Demonstrate the Concept**

Each column in our dataset has a name that describes the customer information it contains.

**Real-Life Example**

CustomerID identifies the customer, Gender shows the customer's gender, and Monthly Charge shows the monthly amount charged.

**AI/ML Usage**

Column names help us identify useful features, target variables.

In [52]:
# All column names
df.columns

Index(['CustomerID', 'Count', 'Country', 'State', 'City', 'Zip Code',
       'Lat Long', 'Latitude', 'Longitude', 'Gender', 'Senior Citizen',
       'Partner', 'Dependents', 'Tenure Months', 'Phone Service',
       'Multiple Lines', 'Internet Service', 'Online Security',
       'Online Backup', 'Device Protection', 'Tech Support', 'Streaming TV',
       'Streaming Movies', 'Contract', 'Paperless Billing', 'Payment Method',
       'Monthly Charges', 'Total Charges', 'Churn Label', 'Churn Value',
       'Churn Score', 'CLTV', 'Churn Reason'],
      dtype='object')

**Interpretation**

- Displays all column names in the dataset.
- Each column name represents a specific type of customer information.

## **5. Index**



**Understand the Concept**

The index is used to identify the position of each row in a dataset.

**Demonstrate the Concept**

By default, Pandas assigns index values starting from 0.

**Real-Life Example**

If a dataset has 7,043 customers, the index helps identify the position of each customer record.

**AI/ML Usage**

The index helps organize and access data, but it is usually not used as a feature for Machine Learning.

In [53]:
# Display the dataset index
df.index

RangeIndex(start=0, stop=7043, step=1)

**Interpretation**

- The index shows the position of each row.
- It helps identify and access dataset records.

## **6. head()**



**Understand the Concept**

The head() function displays the first few rows of a dataset.

**Demonstrate the Concept**

By default, head() displays the first 5 rows.

**Real-Life Example**

When working with a large customer dataset, head() helps us quickly view the first few customer records.

**AI/ML Usage**

head() helps us quickly check whether the dataset is loaded correctly before starting 
Machine Learning.

In [54]:
# head() - 1st 5 rows
df.head()

,CustomerID,Count,Country,State,City,Zip Code,Lat Long,Latitude,Longitude,Gender,...,Contract,Paperless Billing,Payment Method,Monthly Charges,Total Charges,Churn Label,Churn Value,Churn Score,CLTV,Churn Reason
0,3668-QPYBK,1,United States,California,Los Angeles,90003,"33.964131, -118.272783",33.964131,-118.272783,Male,...,Month-to-month,Yes,Mailed check,53.85,108.15,Yes,1,86,3239,Competitor made better offer
1,9237-HQITU,1,United States,California,Los Angeles,90005,"34.059281, -118.30742",34.059281,-118.307420,Female,...,Month-to-month,Yes,Electronic check,70.70,151.65,Yes,1,67,2701,Moved
2,9305-CDSKC,1,United States,California,Los Angeles,90006,"34.048013, -118.293953",34.048013,-118.293953,Female,...,Month-to-month,Yes,Electronic check,99.65,820.5,Yes,1,86,5372,Moved
3,7892-POOKP,1,United States,California,Los Angeles,90010,"34.062125, -118.315709",34.062125,-118.315709,Female,...,Month-to-month,Yes,Electronic check,104.80,3046.05,Yes,1,84,5003,Moved
4,0280-XJGEX,1,United States,California,Los Angeles,90015,"34.039224, -118.266293",34.039224,-118.266293,Male,...,Month-to-month,Yes,Bank transfer (automatic),103.70,5036.3,Yes,1,89,5340,Competitor had better devices

**Interpretation**

- The output displays the first 5 rows of the dataset.
- It helps us quickly understand the dataset structure.

## **7. tail()**



**Understand the Concept**

The tail() function displays the last few rows of a dataset.

**Demonstrate the Concept**

By default, tail() displays the last 5 rows.



**Real-Life Example**

In a large customer dataset, tail() helps us quickly view the last few customer records.

**AI/ML Usage**

tail() helps us inspect the end of the dataset and check whether the data is loaded correctly.

In [55]:
# tail() - last 5 rows
df.tail()

,CustomerID,Count,Country,State,City,Zip Code,Lat Long,Latitude,Longitude,Gender,...,Contract,Paperless Billing,Payment Method,Monthly Charges,Total Charges,Churn Label,Churn Value,Churn Score,CLTV,Churn Reason
7038,2569-WGERO,1,United States,California,Landers,92285,"34.341737, -116.539416",34.341737,-116.539416,Female,...,Two year,Yes,Bank transfer (automatic),21.15,1419.4,No,0,45,5306,NaN
7039,6840-RESVB,1,United States,California,Adelanto,92301,"34.667815, -117.536183",34.667815,-117.536183,Male,...,One year,Yes,Mailed check,84.80,1990.5,No,0,59,2140,NaN
7040,2234-XADUH,1,United States,California,Amboy,92304,"34.559882, -115.637164",34.559882,-115.637164,Female,...,One year,Yes,Credit card (automatic),103.20,7362.9,No,0,71,5560,NaN
7041,4801-JZAZL,1,United States,California,Angelus Oaks,92305,"34.1678, -116.86433",34.167800,-116.864330,Female,...,Month-to-month,Yes,Electronic check,29.60,346.45,No,0,59,2793,NaN
7042,3186-AJIEK,1,United States,California,Apple Valley,92308,"34.424926, -117.184503",34.424926,-117.184503,Male,...,Two year,Yes,Bank transfer (automatic),105.65,6844.5,No,0,38,5097,NaN

**Interpretation**

- The output displays the last 5 rows of the dataset.
- It helps us inspect the records at the end of the dataset.

## **8. sample()**



**Understand the Concept**

The sample() function displays random rows from a dataset.

**Demonstrate the Concept**

It helps us view different records instead of only the first or last rows.


**Real-Life Example**

In a large customer dataset, sample() can be used to randomly check customer records.

**AI/ML Usage**

sample() helps us quickly inspect random data and understand whether the dataset contains different types of records.

In [56]:
# sample() - random rows
df.sample(5)

,CustomerID,Count,Country,State,City,Zip Code,Lat Long,Latitude,Longitude,Gender,...,Contract,Paperless Billing,Payment Method,Monthly Charges,Total Charges,Churn Label,Churn Value,Churn Score,CLTV,Churn Reason
5224,5914-XRFQB,1,United States,California,Caspar,95420,"39.361283, -123.784599",39.361283,-123.784599,Male,...,Two year,Yes,Bank transfer (automatic),115.80,8424.9,No,0,80,6479,NaN
930,1624-NALOJ,1,United States,California,La Puente,91744,"34.031441, -117.936436",34.031441,-117.936436,Male,...,Month-to-month,Yes,Electronic check,89.80,502.6,Yes,1,88,2960,Moved
5557,0567-XRHCU,1,United States,California,Los Angeles,90049,"34.091829, -118.491244",34.091829,-118.491244,Female,...,Two year,Yes,Credit card (automatic),43.95,2960.1,No,0,73,4479,NaN
755,0495-RVCBF,1,United States,California,Santa Rosa,95401,"38.460517, -122.790335",38.460517,-122.790335,Female,...,Month-to-month,Yes,Electronic check,79.70,79.7,Yes,1,75,2066,Don't know
923,2165-VOEGB,1,United States,California,Burbank,91501,"34.188339, -118.300942",34.188339,-118.300942,Female,...,One year,Yes,Bank transfer (automatic),105.20,4822.85,Yes,1,99,3322,Don't know

**Interpretation**

- The output displays 5 random customer records.
- Each time, different rows may be displayed.

## **9. shape**



**Understand the Concept**

The shape attribute shows the number of rows and columns in a dataset.

**Demonstrate the Concept**

It returns the dataset dimensions in the format rows and columns.

**Real-Life Example**

A telecom company dataset with 7,043 customer records and 33 columns has a shape of 7043 rows and 33 columns.

**AI/ML Usage**

The shape helps us understand the size of the dataset before performing building a Machine Learning model.

In [57]:
# shape - rows & col
df.shape

(7043, 33)

**Interpretation**

- The dataset has 7,043 rows.
- The dataset has 33 columns.
- It helps us quickly understand the dataset size.

## **10. info()**



**Understand the Concept**

The info() function displays a summary of the dataset.

**Demonstrate the Concept**

It shows the column names, data types, non-null values, and memory usage.


**Real-Life Example**

For a customer dataset, info() helps us quickly check how many columns are available and whether any values are missing.

**AI/ML Usage**

info() helps us understand the dataset structure and identify possible data issues before Machine Learning.

In [58]:
# info() - dataset information
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 33 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   CustomerID         7043 non-null   object
 1   Count              7043 non-null   int64
 2   Country            7043 non-null   object
 3   State              7043 non-null   object
 4   City               7043 non-null   object
 5   Zip Code           7043 non-null   int64
 6   Lat Long           7043 non-null   object
 7   Latitude           7043 non-null   float64
 8   Longitude          7043 non-null   float64
 9   Gender             7043 non-null   object
 10  Senior Citizen     7043 non-null   object
 11  Partner            7043 non-null   object
 12  Dependents         7043 non-null   object
 13  Tenure Months      7043 non-null   int64
 14  Phone Service      7043 non-null   object
 15  Multiple Lines     7043 non-null   object
 16  Internet Service   7043 non-null   object
 17  Online Security    7043 non-null   object
 18  Online Backup      7043 non-null   object
 19  Device Protection  7043 non-null   object
 20  Tech Support       7043 non-null   object
 21  Streaming TV       7043 non-null   object
 22  Streaming Movies   7043 non-null   object
 23  Contract           7043 non-null   object
 24  Paperless Billing  7043 non-null   object
 25  Payment Method     7043 non-null   object
 26  Monthly Charges    7043 non-null   float64
 27  Total Charges      7043 non-null   object
 28  Churn Label        7043 non-null   object
 29  Churn Value        7043 non-null   int64
 30  Churn Score        7043 non-null   int64
 31  CLTV               7043 non-null   int64
 32  Churn Reason       1869 non-null   object
dtypes: float64(3), int64(6), object(24)
memory usage: 1.8+ MB

**Interpretation**

- The output shows the dataset structure.
- It displays column names and data types.
- It shows the number of non-null values.
- It helps identify possible missing values and data issues.

## **11. describe()**



**Understand the Concept**

The describe() function provides a statistical summary of numerical columns.

**Demonstrate the Concept**

It shows values such as count, mean, standard deviation, minimum, maximum, and percentiles.

**Real-Life Example**

For Monthly Charge, describe() helps us understand the average, minimum, and maximum amount paid by customers.

**AI/ML Usage**

describe() helps us understand the distribution and range of numerical data before analysis and Machine Learning.

In [59]:
# describe() - statistical summary
df.describe()

,Count,Zip Code,Latitude,Longitude,Tenure Months,Monthly Charges,Churn Value,Churn Score,CLTV
count,7043.0,7043.000000,7043.000000,7043.000000,7043.000000,7043.000000,7043.000000,7043.000000,7043.000000
mean,1.0,93521.964646,36.282441,-119.798880,32.371149,64.761692,0.265370,58.699418,4400.295755
std,0.0,1865.794555,2.455723,2.157889,24.559481,30.090047,0.441561,21.525131,1183.057152
min,1.0,90001.000000,32.555828,-124.301372,0.000000,18.250000,0.000000,5.000000,2003.000000
25%,1.0,92102.000000,34.030915,-121.815412,9.000000,35.500000,0.000000,40.000000,3469.000000
50%,1.0,93552.000000,36.391777,-119.730885,29.000000,70.350000,0.000000,61.000000,4527.000000
75%,1.0,95351.000000,38.224869,-118.043237,55.000000,89.850000,1.000000,75.000000,5380.500000
max,1.0,96161.000000,41.962127,-114.192901,72.000000,118.750000,1.000000,100.000000,6500.000000

**Interpretation**

- The output provides a statistical summary of numerical columns.
- It shows the average, minimum, maximum, and other statistical values.

## **12. dtypes**



**Understand the Concept**

The dtypes attribute shows the data type of each column.

**Demonstrate the Concept**

It helps us identify whether a column contains numbers, text, or other types of data.

**Real-Life Example**

Tenure Months may have a numerical data type, while Gender may have an object data type.

**AI/ML Usage**

Data types help us decide how each column should be handled before building a Machine Learning model.

In [60]:
# dtypes - data type of columns
df.dtypes

CustomerID            object
Count                  int64
Country               object
State                 object
City                  object
Zip Code               int64
Lat Long              object
Latitude             float64
Longitude            float64
Gender                object
Senior Citizen        object
Partner               object
Dependents            object
Tenure Months          int64
Phone Service         object
Multiple Lines        object
Internet Service      object
Online Security       object
Online Backup         object
Device Protection     object
Tech Support          object
Streaming TV          object
Streaming Movies      object
Contract              object
Paperless Billing     object
Payment Method        object
Monthly Charges      float64
Total Charges         object
Churn Label           object
Churn Value            int64
Churn Score            int64
CLTV                   int64
Churn Reason          object
dtype: object

**Interpretation**

- The output shows the data type of every column.
- It helps identify numerical and categorical columns.

## **13. nunique()**



**Understand the Concept**

The nunique() function shows the number of unique values in a column.

**Demonstrate the Concept**

It helps us understand how many different values are present in the data.

**Real-Life Example**

The Gender column may contain two unique values: Male and Female.

**AI/ML Usage**

nunique() helps identify categorical columns, identifier columns, and columns with many unique values.

In [61]:
# nunique() - no of unique values in each column
df.nunique()

CustomerID           7043
Count                   1
Country                 1
State                   1
City                 1129
Zip Code             1652
Lat Long             1652
Latitude             1652
Longitude            1651
Gender                  2
Senior Citizen          2
Partner                 2
Dependents              2
Tenure Months          73
Phone Service           2
Multiple Lines          3
Internet Service        3
Online Security         3
Online Backup           3
Device Protection       3
Tech Support            3
Streaming TV            3
Streaming Movies        3
Contract                3
Paperless Billing       2
Payment Method          4
Monthly Charges      1585
Total Charges        6531
Churn Label             2
Churn Value             2
Churn Score            85
CLTV                 3438
Churn Reason           20
dtype: int64

**Interpretation**

- The output shows the number of unique values in each column.
- It helps us understand the variety of values in the dataset.
- It can help identify different types of columns.

## **14. value_counts()**



**Understand the Concept**

The value_counts() function shows how many times each value appears in a column.

**Demonstrate the Concept**

It helps us understand the frequency of different values in a column.

**Real-Life Example**

The Gender column can show how many customers are Male and how many are Female.

**AI/ML Usage**

value_counts() helps us understand category distribution and identify possible class imbalance.

In [62]:
# value_counts() - Count the values in a col
df["Gender"].value_counts()

Gender
Male      3555
Female    3488
Name: count, dtype: int64

**Interpretation**

- The output shows the count of each value.
- It helps us understand the distribution of categories.
- It can help identify imbalance in categorical data.

## **15. Numerical Columns**


**Understand the Concept**

Numerical columns contain number-based values on which mathematical operations can be performed.

**Demonstrate the Concept**

Numerical columns can be:

- Discrete values such as counts
- Continuous values such as charges or measurements

**AI/ML Usage**

Numerical features can be used for prediction, classification, regression, clustering, and statistical analysis.

In [63]:
# numerical columns
numerical_columns = df.select_dtypes(include="number").columns
print(numerical_columns)

Index(['Count', 'Zip Code', 'Latitude', 'Longitude', 'Tenure Months',
       'Monthly Charges', 'Churn Value', 'Churn Score', 'CLTV'],
      dtype='object')

**Interpretation**

- The output displays all numerical columns in the dataset.
- These columns contain number-based values.

## **16. Categorical Columns**



**Understand the Concept**

Categorical columns contain values that represent groups or categories.

**Demonstrate the Concept**

These columns usually contain text values such as Yes, No, Male, Female, or different service types.

**AI/ML Usage**

Most Machine Learning models require numerical input. Therefore, categorical features may need to be converted into numerical values before training a model.

In [64]:
# categorical columns
categorical_columns = df.select_dtypes(include="object").columns
print(categorical_columns)

Index(['CustomerID', 'Country', 'State', 'City', 'Lat Long', 'Gender',
       'Senior Citizen', 'Partner', 'Dependents', 'Phone Service',
       'Multiple Lines', 'Internet Service', 'Online Security',
       'Online Backup', 'Device Protection', 'Tech Support', 'Streaming TV',
       'Streaming Movies', 'Contract', 'Paperless Billing', 'Payment Method',
       'Total Charges', 'Churn Label', 'Churn Reason'],
      dtype='object')

**Interpretation**

- The output displays columns with categorical values.
- These columns represent different groups or categories.
- Some categorical columns may need encoding before using them in a Machine Learning model.

## **17. Date/Time Columns**



**Understand the Concept**

Date/time columns contain date or time-related information.

**Demonstrate the Concept**

They can be used to extract information such as year, month, day, or time.

**Real-Life Example**

A telecom company may store the customer joining date. From this, we can find how long the customer has been with the company.

**AI/ML Usage**

Date/time columns can be converted into useful features such as year, month, day, or customer tenure.

In [65]:
# date/time columns
datetime_columns = df.select_dtypes(include="datetime").columns
print(datetime_columns)

Index([], dtype='object')

**Interpretation**

- Our dataset does not contain any date/time columns.

## **18. Identifier Columns**



**Understand the Concept**

Identifier columns are used to uniquely identify each record in a dataset.

**Demonstrate the Concept**

In our dataset, CustomerID is used to uniquely identify each customer.

**Real-Life Example**

A telecom company gives each customer a unique CustomerID to manage and identify customer records.

**AI/ML Usage**

Identifier columns are usually not used as input features because they do not provide meaningful information for prediction.

In [66]:
# Identifier Columns - unique values in col
df["CustomerID"].nunique()

7043

**Interpretation**

- CustomerID is an identifier column.
- Each customer has a unique ID.
- This column is mainly used to identify customer records.

## **19. Potential Target Columns**



**Understand the Concept**

A target column is the column that we want to predict using a Machine Learning model.

**Demonstrate the Concept**

In our dataset, Churn Label and Churn Value represent customer churn.

Churn Label contains Yes and No, while Churn Value contains 1 and 0.

**Real-Life Example**

- A telecom company wants to predict whether a customer will leave the company.
- Churn Label can be used as the target variable.

**AI/ML Usage**

In supervised Machine Learning:

- Features are represented as X.
- The target variable is represented as y.

Customer information can be used as X, and Churn Label can be used as y.

In [67]:
# values in Churn Label
df["Churn Label"].value_counts()

Churn Label
No     5174
Yes    1869
Name: count, dtype: int64

**Interpretation**

- Churn Label is a potential target column.
- It shows whether a customer left or stayed.
- It can be predicted using customer-related features.